all:
  hosts:
    192.168.99.21:
  vars:
    ansible_user: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod:
  hosts:
    192.168.99.21:
  vars:
    ansible_password: vagrant
    env: production
