# Début d'un play (bloc d'exécution)
- name: "Apache installation using Docker"  # Titre descriptif du play
  hosts: prod                                # S'applique au groupe d'hôtes "prod"
  become: true                               # Active l'élévation de privilèges (sudo)

  vars:
    ansible_sudo_pass: admin                # Mot de passe sudo si nécessaire (non recommandé en clair)

  pre_tasks:                                 # Tâches à exécuter avant les tasks principales
    - name: Install EPEL repo (only for CentOS)  # Installe le dépôt EPEL pour CentOS
      package:
        name: epel-release                  # Nom du paquet à installer
        state: present                      # S'assure que le paquet est présent
      when: ansible_distribution == "CentOS"  # Ne s'exécute que si le système est CentOS

    - name: Ensure Python 3 and pip3 are installed  # Installe Python 3 et pip3 sur Ubuntu
      apt:
        name:
          - python3                         # Paquet Python 3
          - python3-pip                     # pip pour Python 3
        state: present
      when: ansible_distribution == "Ubuntu"  # Ne s'exécute que sur Ubuntu

    - name: Install docker Python module for Python 3  # Installe le module Python "docker"
      pip:
        name: docker                        # Nom du package pip à installer
        executable: pip3                    # Utilise pip3 (lié à Python 3)

  tasks:                                      # Bloc de tâches principales
    - name: Create Apache container           # Crée un conteneur Docker avec Apache
      docker_container:
        name: webapp                         # Nom du conteneur
        image: httpd                         # Image Docker utilisée (Apache HTTP Server)
        ports:
          - "80:80"                          # Redirige le port 80 de l'hôte vers le conteneur
