- name: Installation Docker via script officiel
  hosts: all
  become: true  # Utiliser les privilèges sudo

  tasks:

    - name: Mettre à jour les paquets
      apt:
        update_cache: yes  # Équivaut à `apt update`

    - name: Installer les dépendances
      apt:
        name:
          - apt-transport-https  # Nécessaire pour HTTPS avec apt
          - ca-certificates      # Permet de vérifier les certificats SSL
          - curl                 # Utilitaire pour télécharger des fichiers
          - software-properties-common  # Pour ajouter des dépôts facilement
        state: present

    - name: Ajouter la clé GPG de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg  # Clé publique pour authentifier les paquets Docker
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable  # Dépôt officiel Docker pour Ubuntu 20.04 (Focal)
        state: present

    - name: Mettre à jour le cache APT après ajout du dépôt
      apt:
        update_cache: yes  # Recharger la liste des paquets (avec le nouveau dépôt)

    - name: Installer Docker CE
      apt:
        name: docker-ce  # Docker Community Edition
        state: present

    - name: Démarrer et activer Docker
      systemd:
        name: docker
        enabled: true  # Démarrage automatique au boot
        state: started  # Démarrer le service immédiatement

    - name: Installer pip3
      apt:
        name: python3-pip
        state: present  # pip sera utilisé pour installer le module Python 'docker'

    - name: Installer la bibliothèque docker via pip
      pip:
        name: docker  # Nécessaire pour le module Ansible `docker_container`
        executable: pip3

    # - name: Créer un conteneur Docker avec Nginx
    #   docker_container:
    #     name: nginx-container
    #     image: nginx:latest  # Télécharge et utilise l'image officielle de Nginx
    #     state: started
    #     restart_policy: always  # Redémarrage automatique si le conteneur tombe
    #     ports:
    #       - "8080:80"  # Redirige le port 80 du conteneur vers le port 8080 de l'hôte

    - name: Créer un conteneur Docker avec Apache (httpd)
      docker_container:
        name: apache-container
        image: httpd:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"

